global:
    resolve_timeout: 1m
   

route:
 receiver: 'email'
 
receivers: 
- name: 'email'    
  email_configs:
  - to: shanutelepacket9@gmail.com
    from:  shanutelepacket9@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username:  shanutelepacket9@gmail.com
    auth_identity:  shanutelepacket9@gmail.com
    auth_password: 
    send_resolved: true

