global:
    resolve_timeout: 1m
route:
    receiver: 'gmail'
    repeat_interval: 1m
receivers:
    - name: 'gmail'
      email_configs:
          - to: jay8900@gmail.com
            from: jay8900@gmail.com
            smarthost: smtp.gmail.com:587
            auth_username: jay8900@gmail.com
            auth_identity: jay8900@gmail.com
            auth_password: ljrshdtwwnnjjxqh
            send_resolved: true
      slack_configs:
          - api_url: 'https://hooks.slack.com/services/qwsedrfgthyjgkhljkhgfd'
            channel: '#channel-name'
            send_resolved: true
