global:
    resolve_timeout: 1m
    
route:
 receiver: "email"

receivers: 
- name: 'email'    
  email_configs:
  - to: shanumodi9@gmail.com
    from: shanumodi9@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: shanumodi9@gmail.com
    auth_identity: shanumodi9@gmail.com
    auth_password: ${{ secrets.PASSWORD }}
    send_resolved: true


  slack_configs:
  - api_url: 'https://hooks.slack.com/services/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'
    channel: 'testing-channel'
    send_resolved: true
