global:
    resolve_timeout: 1m

route:
    receiver: 'gmail'

receivers:
    - name: 'gmail'
      email_configs:
          - to: varghesekurian161@gmail.com
            from: varghesekurian161@gmail.com
            smarthost: smtp.gmail.com:587
            auth_username: varghesekurian161@gmail.com
            auth_identity: varghesekurian161@gmail.com
            auth_password: cbdukvtozaggrqgl
            send_resolved: true
