global:
    resolve_timeout: 1m
    slack_api_url: 'https://hooks.slack.com/services/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'
route:
 receiver: 'email'
 
receivers: 
- name: 'email'    
  email_configs:
  - to: shanutelepacket9@gmail.com
    from: shanutelepacket9@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: shanutelepacket9@gmail.com
    auth_identity: shanutelepacket9@gmail.com
    auth_password: ${{ secrets.password }}
    send_resolved: true


  slack_configs:
  - channel: 'testing-channel'
    send_resolved: true
